[project]
name = 'review-incentive'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.review-incentive]
path = 'contracts/review-incentive.clar'
clarity_version = 3
epoch = 3.1
[contracts.review-challenges]
path = 'contracts/review-challenges.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
